### ISSUE TITLE
SVG has 0 byte size (empty)

### ISSUE THREAD

**Issue by doniwinata** [rschlaikjer/erlang-atrace-flamegraphs#3]
Hi @rschlaikjer , I follow the instructions to run on my local machine (Mac OS), and the website already launched successfully. However, when i uploaded my trace file, it shows empty page with a title on top of it (A6E3FB43121C7F8C76948513BF121785). Do you know what might be wrong here ? i just checked the file is generated for index.html and temporary .trace file, as well as dozen of SVG files. However all of the SVG files are empty (zero byte).
Thank you in advance

**Comment by rschlaikjer** [comment]
Hi Doni,

Have you downloaded Brendan Gregg's [flamegraph.pl](https://github.com/brendangregg/FlameGraph/blob/master/flamegraph.pl) and added it to somewhere in `$PATH`?
Make sure that it has been renamed to simply `flamegraph`, since this is the command that will be executed:
https://github.com/rschlaikjer/erlang-atrace-flamegraphs/blob/06b85c05a37b48c78ec7d584bc2eacfd3b4a3fc2/src/aflame_grapher_worker.erl#L162-L171

**Comment by doniwinata** [comment]
my bad, i haven't add that script on my $PATH, thank you very much for your fast response, really appreciated 👍
