### ISSUE TITLE
Docker container exited(137)

### ISSUE THREAD

**Issue by TheSpartan94** [rschlaikjer/erlang-atrace-flamegraphs#5]
The docker container is exiting on very big trace file sizes (128.9MB), probably for an OutOfMemory exception.

Is there a fast solution to avoid this?

**Comment by rschlaikjer** [comment]
Is this running locally? If so, can you confirm that the reason is memory? What error logs do you have regarding the exit? It should be possible to set the max memory for a docker container with the `--memory` flag.
If you have uploaded it to aflame.rhye.org, if you tell me the hash of the file I can look into it.

**Comment by rschlaikjer** [comment]
Testing on a different 128MiB file, I see memory spikes up to 5Gb :grimacing: 
I haven't touched this code in some time, so I'm sure there is room for optimization. The fastest workaround would be to allocate more memory to the container, or if your trace data is not sensitive, use the online service.
![2020-04-15-100936_2057x1479_scrot](https://user-images.githubusercontent.com/2476799/79347175-53739500-7f01-11ea-8627-8e11d3ede08e.png)

**Comment by TheSpartan94** [comment]
Problem solved by allocating up to 3GB of RAM for the container. I've seen the RAM getting cleaned like 3 times. Sure there's room for optimization, i think you can clean up data more often.

By the way, if I were in you, I'd suggest in the README file to increase the memory allocated for the container. Thanks a lot.
